name: Temp and Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v5
      - name: install dependencies
        run: |
          uv lock
          uv sync
      - name: run tests
        run: |
          uv run -m unittest
      
